### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by JohnReedLOL** [julienrf/pfe-samples#1]
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

Server started, use Alt+D to stop

[info] Compiling 22 Scala sources and 1 Java source to /home/johnreedlol/IdeaProjects/pfescala/target/scala-2.10/classes...
[error] /home/johnreedlol/IdeaProjects/pfescala/app/controllers/Authentication.scala:34: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]             BadRequest(views.html.login(submission.withGlobalError(Messages("auth.unknown", username)), returnTo))
[error]                                                                            ^
[error] /home/johnreedlol/IdeaProjects/pfescala/app/controllers/Items.scala:47: could not find implicit value for parameter lang: play.api.i18n.Messages
[error]         case Accepts.Json() => BadRequest(formWithErrors.errorsAsJson)
[error]                                                          ^
[error] /home/johnreedlol/IdeaProjects/pfescala/app/controllers/Items.scala:77: could not find implicit value for parameter lang: play.api.i18n.Messages
[error]       formWithErrors => BadRequest(formWithErrors.errorsAsJson),
[error]                                                   ^
[error] /home/johnreedlol/IdeaProjects/pfescala/app/views/createForm.scala.html:5: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         @helper.inputText(form("name"), '_label -> "Name")
[error]                          ^
[error] /home/johnreedlol/IdeaProjects/pfescala/app/views/login.scala.html:11: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         @helper.inputText(form("username"), '_label -> "Name")
[error]                          ^
[error] /home/johnreedlol/IdeaProjects/pfescala/app/views/main.scala.html:6: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         <title>@Messages("index")</title>
[error]                         ^
[error] 6 errors found
[error](pfescala/compile:compile) Compilation failed
[error] application - 

! @6p2k9bh59 - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$CompilationException: Compilation error[could not find implicit value for parameter messages: play.api.i18n.Messages]
    at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
    at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
    at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
    at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
    at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
    at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
    at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
    at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]

plugins.sbt looks like this...

// Comment to get more information during initialization
// logLevel := Level.Warn

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.2")

addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.2")

addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.5")

addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")

addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.0.0")

^ Note that by default IntelliJ is using ("com.typesafe.play" % "sbt-plugin" % "2.4.2") instead of ("com.typesafe.play" % "sbt-plugin" % "2.3.4") ^

**Comment by JohnReedLOL** [comment]
Note, changing to ("com.typesafe.play" % "sbt-plugin" % "2.3.4") fixed the problem, but the example should be updated to work with ("com.typesafe.play" % "sbt-plugin" % "2.4.2")

**Comment by JohnReedLOL** [comment]
Also, "Symbol Routes is deprecated. Use play.api.routing.Router instead"

**Comment by JohnReedLOL** [comment]
"Symbol Routes is deprecated. Use play.api.routing.Router instead" in Application.scala

```
/* val router = Routes.javascriptRouter("routes")( */

val router = JavaScriptReverseRouter("routes")(
  routes.javascript.Items.delete,
  routes.javascript.Auctions.bid,
  routes.javascript.Auctions.notifications,
  routes.javascript.Auctions.channel
)
```

**Comment by julienrf** [comment]
Well, I’d like the code repository to be in sync with the book content, which targets Play 2.3. I started to update the code repository in a [separate branch](https://github.com/julienrf/pfe-samples/tree/play-2.4.0) to work with Play 2.4, but I’m not sure it still works.

**Comment by JohnReedLOL** [comment]
Also, glancing at code, hard to tell what "ws" stands for (especially in controller/routes) - I would rename to "websocket".

**Comment by JohnReedLOL** [comment]
I don't actually know how to use SBT - I just make a new Play2 project in IntelliJ and then copy-paste the files in. Will make sure it works with Play 2.4.2 later.

**Comment by JohnReedLOL** [comment]
Also, one little think. In some places "ws" stands for "web service" (i.e. service.scala) and in other places "ws" stands for "web socket". Super confusing, especially when you first look at the code.

**Comment by JohnReedLOL** [comment]
[error] /media/ramdisk/NoMoreProjects/pfe-scala/service/src/main/scala/loaders/ShopServiceComponents.scala:6: object evolutions is not a member of package play.api.db
[error] import play.api.db.evolutions.{DynamicEvolutions, EvolutionsComponents}
[error]                    ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/service/src/main/scala/loaders/ShopServiceComponents.scala:13: not found: type EvolutionsComponents
[error]     with EvolutionsComponents with AkkaComponents {
[error]          ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/service/src/main/scala/loaders/ShopServiceComponents.scala:15: not found: type DynamicEvolutions
[error]   val dynamicEvolutions = new DynamicEvolutions // WTF???
[error]                               ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/service/src/main/scala/loaders/ShopServiceComponents.scala:16: not found: value applicationEvolutions
[error]   applicationEvolutions // Force the application of evolutions, if needed
[error]   ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/service/src/main/scala/loaders/ShopServiceComponents.scala:23: value Null is not a member of object play.core.Router
[error]   def routes: Router.Routes = Router.Null
[error]                                      ^
[error] 5 errors found

  val dynamicEvolutions = new DynamicEvolutions // WTF???
  applicationEvolutions // Force the application of evolutions, if needed

**Comment by JohnReedLOL** [comment]
[info] Compiling 22 Scala sources and 1 Java source to /media/ramdisk/NoMoreProjects/pfe-scala/target/scala-2.11/classes...
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/controllers/Authentication.scala:29: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]             BadRequest(views.html.login(submission.withGlobalError(Messages("auth.unknown", username)), returnTo))
[error]                                                                            ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/controllers/Items.scala:42: could not find implicit value for parameter lang: play.api.i18n.Messages
[error]         case Accepts.Json() => BadRequest(formWithErrors.errorsAsJson)
[error]                                                          ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/controllers/Items.scala:72: could not find implicit value for parameter lang: play.api.i18n.Messages
[error]       formWithErrors => BadRequest(formWithErrors.errorsAsJson),
[error]                                                   ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/views/createForm.scala.html:5: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         @helper.inputText(form("name"), '_label -> "Name")
[error]                          ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/views/createForm.scala.html:6: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         @helper.inputText(form("price"), '_label -> "Price")
[error]                          ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/views/login.scala.html:11: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         @helper.inputText(form("username"), '_label -> "Name")
[error]                          ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/views/login.scala.html:12: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         @helper.inputPassword(form("password"), '_label -> "Password")
[error]                              ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/views/main.scala.html:6: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         <title>@Messages("index")</title>
[error]                         ^
[error] /media/ramdisk/NoMoreProjects/pfe-scala/app/views/main.scala.html:9: could not find implicit value for parameter messages: play.api.i18n.Messages
[error]         <h1>@Messages("index")</h1>
[error]                      ^
[error] 9 errors found
[error] (pfe-scala/compile:compile) Compilation failed
[error] application - 

! @6p3b3ei5e - Internal ser

BadRequest(views.html.login(submission.withGlobalError(Messages("auth.unknown", username)), returnTo))

^ Messages takes implicit parameter messages

**Comment by JohnReedLOL** [comment]
Also, even with the correct Play version number, the compile time dependency injection has massive numbers of red imports [not found] in IntellIJ. As a noob this application is the bedrock of my future application.

**Comment by JohnReedLOL** [comment]
It works, but only with "2.4.0-M2". It would be nice to upgrade it, but I don't know how.

**Comment by julienrf** [comment]
FYI, I added a branch upgrading the Scala sample to Play 2.5.0: https://github.com/julienrf/pfe-samples/tree/play-2.5.0
